lang: pl-PL
babel-lang: polish

title: "Raport z testów bezpieczeństwa"
subtitle: "Biuro Cyberbezpieczeństwa"
date: "2025-08-21"

author: ["Wojciech Dołowy"]
recenzent: ["Jan Kowalski"]
version: "1.0"   # NIE zmieniam – wersja raportu, nie aplikacji

request_number: "1232312"
app_cra: "CRA-123"

work_subject: "Aplikacja XYZ"
work_dates: "2025-08-10 – 2025-08-15"
retest_dates: "-"

titlepage: true
titlepage-color: "111827"
titlepage-text-color: "FFFFFF"
titlepage-rule-color: "4353B3"
titlepage-rule-height: 3
titlepage-logo: "assets/branding/logo.png"
logo-width: "28mm"
titlepage-background: "assets/branding/background.pdf"

footnotes-disable-backlinks: true

toc-own-page: true
fontsize: 11pt
papersize: a4
colorlinks: true
linkcolor: "Link"
urlcolor:  "URL"
citecolor: "Cite"

minted: true
minted-style: "friendly"

header-includes:
  - '\usepackage{placeins}'
  - '\usepackage[export]{adjustbox}'
  - '\usetikzlibrary{calc,positioning}'
  - '\pgfplotsset{compat=1.18}'
  - '\definecolor{Link}{rgb}{0.10,0.10,0.10}'
  - '\definecolor{URL}{rgb}{0.00,0.30,0.55}'
  - '\definecolor{Cite}{rgb}{0.00,0.30,0.55}'
  - '\definecolor{Crit}{HTML}{6D28D9}'
  - '\definecolor{High}{HTML}{DC2626}'
  - '\definecolor{Med}{HTML}{F97316}'
  - '\definecolor{Low}{HTML}{16A34A}'
  - '\definecolor{Info}{HTML}{0EA5E9}'
  - '\graphicspath{{src/}{assets/images/}{assets/branding/}}'
